version: "3.8"

services:
  api:
    container_name: exultant_rhino_api
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8101:8101"
    env_file:
      - .env
    networks:
      - app_network
  app:
    container_name: exultant_rhino_app
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    networks:
      - app_network
networks:
  app_network:
      name: general_network
      external: true