version: "3.8"

services:
  api:
    container_name: er_api
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8101:8101"
    env_file:
      - .env
  app:
    container_name: er_app
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8501:8501"
