version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
#    volumes:
#      - postgres-volume:/var/lib/postgresql/data
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin-volume:/var/lib/pgadmin

volumes:
  postgres-volume:
  pgadmin-volume:
