services:
  app:
    container_name: exultant_rhino_app
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    networks:
      - app_network
networks:
  app_network:
      name: general_network
      external: true
