services:
  app:
    container_name: exultant_rhino_app
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
  api:
    container_name: exultant_rhino_api
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8500:8500"
    env_file:
      - .env
  db:
    image: postgres
    container_name: exultant_rhino_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
volumes:
  postgres-volume:
