version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
        - proxy_net
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
networks:
  proxy_net:
    name: general_network
volumes:
  postgres-volume:
  pgadmin-volume: