[tox]
skipsdist = True
envlist = py310

[common]
deps =  pylint
        pytest
        pytest-html
        selenium
        -r../requirements.txt

[testenv:flask_app]
deps =  -r../requirements.txt
commands = python3.10 ../main.py

[testenv:lint]
deps =  {[common]deps}
commands =  pylint {posargs:py.test} --max-line-length=120 --disable=C0114 --fail-under=9.5

[testenv:unittests]
deps =  {[common]deps}
commands =  pytest -k unittests -v --junitxml=unittests_results.xml

[testenv:upload]
deps =  {[common]deps}
commands =  pytest -k upload -v --junitxml=upload_tests_results.xml

[testenv:selenium]
deps =  {[common]deps}
commands =  pytest -k selenium -v --junitxml=selenium_tests_results.xml