[tox]
skipsdist = True
envlist = py310

[common]
deps =  pylint
        pytest
        pytest-html
        selenium
        -r../requirements.txt

[testenv:lint]
deps =  {[common]deps}
commands =  pylint {posargs:py.test} --max-line-length=120 --disable=C0114 --fail-under=9.0

[testenv:unittests]
deps =  {[common]deps}
commands =  pytest -k unittests -v --junitxml=unittests_results.xml

[testenv:regular]
deps =  {[common]deps}
commands =  pytest -k regular -v --junitxml=regular_tests_results.xml

[testenv:selenium]
deps =  {[common]deps}
commands =  pytest -k selenium -v --junitxml=selenium_tests_results.xml