[tox]
skipsdist = True
envlist = py310

[common]
deps =  pylint
        pytest
        pytest-html
        -r../requirements.txt

[testenv:lint]
deps =  {[common]deps}

commands =  pylint {posargs:py.test} --max-line-length=120 --disable=C0114 --fail-under=8.5

[testenv:database_tests]
deps =  {[common]deps}

commands =  pytest -k database_tests -v --junitxml=database_tests_results.xml