from pymongo import MongoClient


class MongoDb:
    """
    MongoDB is a class to operate on database with usage of pymongo library.
    """

    def __init__(self, db_name, collection_name):
        self.client = MongoClient(host='mongodb', port=27017)
        self.db_name = db_name
        self.collection_name = collection_name

    def insert(self, data):
        """
        insert function inserts given data dict into database collection
        :param data: dict type object, preferably generated by vars() from model class object
        :return: inserted_id value
        """
        return self.client[self.db_name][self.collection_name].insert_one(data).inserted_id

    def find(self, query):
        """
        find function searches for database and returns objects that meet the condition of given query
        :param query: dict type object that consists of searched value
        :return: list of found database objects
        """
        return self.client[self.db_name][self.collection_name].find(query, projection={'_id': False})

    def delete(self, query):
        """
        delete function searches for database and deletes all objects that met the condition of given query
        :param query: dict type object that consists of searched value
        :return: deleted_cound value
        """
        return self.client[self.db_name][self.collection_name].delete_one(query).deleted_count

    def update(self, query, new_data):
        """
        find function searches for database and updates found objects with given data
        :param query: dict type object that consists of searched value
        :param new_data: dict type object, preferably generated by vars() from model class object
        :return: modified_count value
        """
        return self.client[self.db_name][self.collection_name].update_one(query, new_data).modified_count
